---
title: "Linear Regression"
date: "December 10, 2025"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    highlight: pygments
fontsize: 12pt
geometry: margin=1in
urlcolor: blue
header-includes:
  - \usepackage[font=small,labelfont=bf]{caption}
  - \usepackage[default]{lato}
  - \usepackage[scale=0.9]{sourcecodepro}
  - \usepackage[T1]{fontenc}
---

\newpage

# Scatter plot example

```{r}
plot(y = mtcars$mpg, x = mtcars$wt,
     main = "Efficiency as a function of car weight",
     ylab = "Miles per gallon", xlab = "Car weight")

# alternative: plot(mpg~wt, data = mtcars)
```

# Linear model example

```{r}
fit <- lm(formula = mtcars$mpg ~ mtcars$wt)

# alternative: lm(formula = mpg ~ wt, data = mtcars)

plot(y = mtcars$mpg, x = mtcars$wt,
     main = "Efficiency as a function of car weight",
     ylab = "Miles per gallon", xlab = "Car weight")

# Show fitted line
abline(fit)
```

# Measuring the strength of association

$$
H_0: B = 0 \quad \text{(Slope of regression line is zero)}
$$

```{r}
# Get the p-value using `summary()`
summary(fit)
```

```{r}
# To get the p-value of the slope

# This displays the slope and intercept
# along with their p-values 'Pr(>|t|)'
# By default the p-values are two-sided
summary(fit)$coefficients
```

```{r}
# To get goodness of fit
# The model explains '100*r^2' percent of the variance in y
summary(fit)$r.squared
```

# Multiple Regression

```{r}
# Use '+' to add more independent variables (x1,x2,...,xn)
fit_multiple <- lm(mpg~wt+disp,data=mtcars)
summary(fit_multiple)$coefficients
```

# ANOVA

```{r}
# Used when comparing means of multiple categories.
# Used for analyzing the results of an experiment with multiple groups.

# Example

light <-
data.frame(experiment=
letters[c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,
2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,
4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,
5,5,5,5,5,5,5)],speed=c(85,74,90,107,93,85,95,98,98,88,100,98,93,
65,76,81,100,100,96,96,96,94,96,94,88,80,85,88,90,84,83,79,81,88,
88,83,80,79,76,80,88,88,88,86,72,72,62,86,97,95,88,91,85,87,84,84,
85,84,84,84,89,81,81,82,80,77,76,74,75,76,91,92,89,86,88,72,84,85
,85,78,89,84,78,81,76,81,79,81,82,85,87,87,81,74,81,94,95,80,81,87))

head(light)
```

```{r}
# Null: mean_a = mean_b = mean_c = mean_d = mean_e
# To get the p-value
# Since 0.00311 < 0.05 we reject the null
summary(aov(speed~experiment,data=light))
```

